on:
  push:
    branches:
      - feature/lab3
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Add Execute Permissions for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test jacocoTestReport

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
        with:
          args: >
            -Dsonar.projectKey="bhos-qa_lab-3-rgasimzade"
            -Dsonar.organization="bhos-qa"
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=build/classes/java/main